# Change these first
owner: azuracast # Your GitHub organization or username, where this repository lives
repo: status.azuracast.com # The name of this repository

sites:
  - name: AzuraCast Homepage
    url: https://www.azuracast.com
  - name: AzuraCast Docs
    url: https://docs.azuracast.com
  - name: AzuraCast Central
    url: https://central.azuracast.com
  - name: AzuraCast Demo Instance
    url: https://demo.azuracast.com/api/nowplaying/1

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.azuracast.com
  # baseUrl: /your-repo-name
  logoUrl: https://github.com/AzuraCast/AzuraCast/raw/main/resources/icon.svg
  name: AzuraCast
  introTitle: "**AzuraCast** is a free and open-source, self-hosted web radio management suite."
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - BusterNeece

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "5,20,35,50 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
